production:
  password: shptka_536e3677159d9ca7007ce15378dac8e5
  theme_id: 158661935439
  store: sommer33.myshopify.com
  ignore_files:
    - locales/*.json
    - config/settings_data.json
    - templates/*.json